
import java.awt.event.FocusEvent;
import java.awt.event.FocusListener;
import java.io.Serializable;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author rip.Torres! ^-^
 */
public class CampoTextoHint extends javax.swing.JPanel implements Serializable {

    private String hint = "{{CampoTextoHint}}";
    
    /**
     * Creates new form CampoTextoHint
     */
    
    public void setHint(String texto){
        hint = texto;
        jTextField1.setText(hint);
    }
    
    public String getHint(){
        return hint;
    }
    
    public CampoTextoHint() {
        initComponents();
        jTextField1.setText(hint);
        jTextField1.addFocusListener(new FocusListener() {
            @Override
            public void focusGained(FocusEvent fe) {
                if(jTextField1.getText().equals(hint)==true){
                    jTextField1.setText("");
                }
            }

            @Override
            public void focusLost(FocusEvent fe) {
               if(jTextField1.getText().equals("")){
                   jTextField1.setText(hint);
               }
            }
        });
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTextField1)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
